### ISSUE TITLE
In which cases could the initializers fail?

### ISSUE THREAD

**Issue by diegomontoyas** [ashleymills/Reachability.swift#125]
Hi, I'm a little bit confused as to when methods like "Reachability.reachabilityForInternetConnection()" would fail.

Thank you very much.

**Comment by ashleymills** [comment]
Hi,

`reachabilityForInternetConnection()` will fail (throw) if `SCNetworkReachabilityCreateWithAddress` fails and returns nil.

My guess is that this is a pretty unlikely occurrence!

Ash

**Comment by ashleymills** [comment]
@diegomontoyas However - if you take a look at the iOS10 branch, I've changed this into a failable init, rather than throwing. Let me know what you think.

Cheers
Ash

**Comment by bm-w** [comment]
Interpreting from [a reply from an Apple employe on the developer forums](https://devforums.apple.com/message/806071#806071), it seems `SCNetworkReachabilityCreateWithAddress` only returns `NULL` when the address is `NULL` or in the case of memory allocation issues (digging through the [Darwin source](https://opensource.apple.com/source/configd/configd-453.16/SystemConfiguration.fproj/SCNetworkReachability.c) mentioned in that reply confirms this).

In [your code (v3)](https://github.com/ashleymills/Reachability.swift/blob/v3/Reachability/Reachability.swift#L126), you’re passing an address (so we can preclude that failure). The only remaining failure case is due to memory allocation issues, on which Chris Lattner [has said](https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20160411/001725.html) (emphasis mine):

> Swift’s policy on memory allocation failure is that fixed-size object allocation *is considered to be a runtime failure if it cannot be handled*.

_(Note: It seems that they later decided that variable-size object allocation failure is also considered a runtime failure; see e.g. https://github.com/apple/swift-corelibs-foundation/pull/538)_

As such, I think you can safely make the initializer non-failable by force-unwrapping the value returned from `SCNetworkReachabilityCreateWithAddress` (or make it explicit what you’re doing by calling `fatalError`, [like they did in `Data(capacity:Int)`](https://github.com/apple/swift-corelibs-foundation/blob/0742948f4d9d23c01c044fe55526d41cb03ea03e/Foundation/Data.swift#L231)).
