### ISSUE TITLE
podspec lint failing with latest Xcode 7 beta 5

### ISSUE THREAD

**Issue by ashleymills** [ashleymills/Reachability.swift#36]
There's a problem validating the pod spec for 2.0-beta5 at the moment. 
See http://stackoverflow.com/questions/32098766/podspec-lint-failing-with-latest-xcode-beta

If anyone has a solution please leave it here or on SO.

Cheers
Ash

**Comment by 503geek** [comment]
Possibly a related issue, trying to build an app containing Reachability.swift (without using Pods) in Xcode Beta 5 causes a segmentation fault (11) apparently at the initializer:

Snippet of the log:

1.  While type-checking 'init' at /path/removed/for/security/Reachability.swift:85:24

2.  While type-checking declaration 0x7fbffc91a350 at /path/removed/for/security/Reachability.swift:86:9

3.  While type-checking expression at [/path/removed/for/security/Reachability.swift:86:19 - line:86:113] RangeText="SCNetworkReachabilityCreateWithName(nil, (hostname as NSString).UTF8String).takeRetainedValue()"

4.  While type-checking expression at [/path/removed/for/security/Reachability.swift:86:19 - line:86:113] RangeText="SCNetworkReachabilityCreateWithName(nil, (hostname as NSString).UTF8String).takeRetainedValue()"

5.  While type-checking expression at [/path/removed/for/security/Reachability.swift:86:19 - line:86:95] RangeText="SCNetworkReachabilityCreateWithName(nil, (hostname as NSString).UTF8String).t"

 Command failed due to signal: Segmentation fault: 11
