### ISSUE TITLE
Will app get rejected?

### ISSUE THREAD

**Issue by vinbhai4u** [ashleymills/Reachability.swift#59]
I saw in the below link

https://github.com/tonymillion/Reachability

App may be rejected?

Will using Reachability.swift can cause to rejection?

**Comment by ashleymills** [comment]
Short answer… no.

Long answer… The rejections mentioned in the link are due to multiple frameworks using the Objective C Reachability class, resulting in class name collisions.

In Swift, classes are implicitly scoped by the module (Xcode target) they are in, so as long as you only import Reachability once into your main project you'll be fine. If other frameworks use Reachability, it's out of the scope of your main target, so not a problem.

Cheers
Ash
