### ISSUE TITLE
Reachability Notification

### ISSUE THREAD

**Issue by imran87** [ashleymills/Reachability.swift#77]
in the Example - notifications code section it give the error on the below line

reachability.startNotifier()
Error is : Call can throw, but it is not marked with 'try' and the error is not handled

i fixed this error by doing like that
do {
try reachability.startNotifier()
} catch {
print("Unable to start notifier")
}

But it didn't work for me please somebody help quickly

here my system version is OS X El Capitan version 10.11.2
and xcode 7.2

**Comment by ashleymills** [comment]
What do you mean by "it didn't work for me"?

It didn't compile?
It crashed?
It didn't show correct Reachability?

**Comment by MotoxX** [comment]
I did ran into the same issue more or less.
according to you documentation you can start the notifier by using just one line:
`reachability.startNotifier()`

But this will give an error as described above wich can be fixed. But the issue that there will be no notification when reachability changes.

I used you example and the current version via cocapods.

Thanks a lot

**Comment by Vektrat** [comment]
Hello, I've just checked this code out and I may be of help.

1. The provided code does fail to compile because a try/catch appears to be missing - yes
2. You may not be getting notifications because you may have pasted the variable holding the Reachability object in a local scope, or somewhere where it is not retained strongly enough. This object requires a more permanent kind of memory retainment, I recommend you to try again by declaring it as an object variable and see if you get more than one notification.

**Comment by ashleymills** [comment]
@Vektrat thank you for your response to this issue. You are correct - the class needs to have a strong reference to the reachability object (e.g. declaring it in `viewDidLoad` won't work).
